tap "go-swagger/go-swagger"
tap "homebrew-ffmpeg/ffmpeg"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "wercker/wercker"
brew "autoconf"
brew "aws-elasticbeanstalk"
brew "python@3.9", link: false
brew "awscli"
brew "carthage"
brew "cmake"
brew "coreutils"
brew "go"
brew "dep"
brew "direnv"
brew "dnsmasq"
brew "docker", link: false
brew "fdk-aac"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "goenv"
brew "graphviz"
brew "hub"
brew "jq"
brew "mint"
brew "mosquitto"
brew "mysql"
brew "n"
brew "nmap", link: false
brew "node", link: false
brew "nodebrew"
brew "nvm"
brew "openssl@3"
brew "p7zip"
brew "pacvim"
brew "peco"
brew "phpmyadmin"
brew "plantuml"
brew "postgresql@14"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-gemset"
brew "redis"
brew "rename"
brew "sleepwatcher", restart_service: true
brew "tig"
brew "tree"
brew "vim"
brew "watchman"
brew "yarn"
brew "zplug"
brew "go-swagger/go-swagger/go-swagger"
brew "homebrew-ffmpeg/ffmpeg/ffmpeg", args: ["HEAD", "with-fdk-aac"]
brew "wercker/wercker/wercker-cli"
cask "adoptopenjdk"
cask "atom"
cask "docker"
cask "google-cloud-sdk"
cask "intellij-idea"
cask "mactex"
cask "mongodb-compass"
